version: 0.2

env:
  shell: bash
  variables:
    AMI_ID: ""
  exported-variables:
    - AMI_ID

phases:
  install:
    commands:
      - echo "Hello from >>>>>>>>>> buildspec_packer <<<<<<<<<<<"
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update -y
      - apt-get install -y packer
      - apt-get install -y jq

  build:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      - PACKAGE=$(echo $CODEBUILD_SOURCE_VERSION | sed 's/.*:/s3:\/\//')
      - echo $PACKAGE

#      - packer init .
#
#      - packer build -var "package=${PACKAGE}" .
#      - test -s packer-manifest.json || exit 1
#      - AMI_ID=$(jq -r '.builds[-1].artifact_id' packer-manifest.json | cut -d ":" -f2)
      - AMI_ID=ami-0a2609b8026d7aeec

      #      - packer build -var "package=${PACKAGE}" . | tee packer.log
      #      - REGION=eu-north-1
      #      - echo $REGION
      #      - tail packer.log | grep "$REGION:" | sed "s/$REGION:.//"
      - ls -alh
      - echo $AMI_ID
