version: 0.2
env:
  variables:
    SELENIUM_SERVER_URL: http://127.0.0.1:4444/wd/hub
    PASS_RATE: 100
    APP_TARGET_URL: http://16.170.148.183:8080
phases:
  pre_build:
    commands:
      - docker run --detach --publish 4444:4444 --volume /dev/shm:/dev/shm --name selenium selenium/standalone-firefox:3.141.59
      - pip3 install selenium unittest-xml-reporting junitparser
  build:
    commands:
      - |
        python3 scripts/test_func.py \
          --selenium-server-url "${SELENIUM_SERVER_URL}" \
          --app-target-url "${APP_TARGET_URL}" \
          --output ./report.xml \
          --pass-rate "${PASS_RATE}"
reports:
  Selenium:
    file-format: JunitXml
    files:
      - ./report.xml
