version: 0.2
env:
  shell: bash
  variables:
    PACKAGE: "github.com/aws-cd/pyapp"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - apt-get -y install awscli

  #      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
  #      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
  pre_build:
    commands:
        - virtualenv venv

  #      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  #      - apt-get update && apt-get -y install sqlite3 awscli
  #      - cd "/go/src/${PACKAGE}"
  #      - go get -t ./...
  #      - cat schema.sql | sqlite3 tasks.db
  build:
    commands:
        - . venv/bin/activate && pip3 install --upgrade pip && pip install -r requirements.txt && deactivate
  #      - go build -o application
  post_build:
    commands:
#      - aws s3 cp s3://pack-to-deb-script/pack_to_deb.sh ./
#      - bash pack_to_deb.sh application 1.0 tasks golang

#artifacts:
#  files:
#    - './*.deb'
#  discard-paths: yes
