version: 0.2

env:
  shell: bash

phases:

  #  install:
  #    #    runtime-versions:
  #    #      python: 3.8
  #    commands:
  #
  #  #      - apt-get update
  #  #      - apt-get -y install awscli

  pre_build:
    commands:
      - echo "Hello from >>>>>>>>>> buildspec_refresh <<<<<<<<<<<"

  build:
    commands:
      - echo $AMI_ID
      - TEMPLATE_ID=$(aws ec2 describe-launch-templates --query "LaunchTemplates[?LaunchTemplateName=='pyapp-test-3'].LaunchTemplateId" --output text)
      - echo $TEMPLATE_ID
      - aws ec2 create-launch-template-version --launch-template-id $TEMPLATE_ID --source-version 1 --launch-template-data ImageId=$AMI_ID --output table
      - aws autoscaling start-instance-refresh --auto-scaling-group-name DEV-asg

  post_build:
    commands:
#      - aws s3 cp s3://pack-to-deb-script/pack_to_deb.sh ./
#      - bash ./scripts/pack_to_deb.sh blog.py 1.0 blog python

#artifacts:
#  files:
#    #    - './*.deb'
#    - '**/*'
#  discard-paths: yes