version: 0.2
env:
  shell: bash
  variables:
    PACKAGE: "github.com/aws-cd/pyapp"
phases:

  install:
    runtime-versions:
      python: 3.8
    commands:

      - apt-get update
      - apt-get -y install awscli

  pre_build:
    commands:

  build:
    commands:
      - chmod +x run.sh

  post_build:
    commands:
      - aws s3 cp s3://pack-to-deb-script/pack_to_deb.sh ./
      - bash pack_to_deb.sh blog.py 1.0 pyapp python

artifacts:
  files:
    - './*.deb'
  discard-paths: yes


#just to restart Code Pipeline 1
