# BROKER_URL = 'redis://redis:6379'
# CELERY_RESULT_BACKEND = 'redis://redis:6379'

SECRET_KEY = 'bmnkvsk'
SQLALCHEMY_DATABASE_URI = 'sqlite:///jwtblog.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_SECRET_KEY = 'bmnkvsk'
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']
JWT_TOKEN_LOCATION = ['headers', 'cookies']
JWT_COOKIE_CSRF_PROTECT = False
JWT_CSRF_CHECK_FORM = False
PROPAGATE_EXCEPTIONS = True
MY_CONF_PARM = 33

BOT_NUMBER_OF_USERS = 2
BOT_MAX_POSTS_PER_USER = 20
BOT_MAX_LIKES_PER_USER = 20
