# ----- App configuration section -----
SECRET_KEY = '222bmnkvsk777'
SQLALCHEMY_DATABASE_URI = 'sqlite:///jwtblog.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_SECRET_KEY = '777kjnpsj222'
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access']
JWT_TOKEN_LOCATION = ['headers', 'cookies']
JWT_COOKIE_CSRF_PROTECT = False
JWT_CSRF_CHECK_FORM = False
PROPAGATE_EXCEPTIONS = True

# ----- Blog Bot configuration section -----
BOT_NUMBER_OF_USERS = 5
BOT_MAX_POSTS_PER_USER = 10
BOT_MAX_LIKES_PER_USER = 20
